### ISSUE TITLE
Indian Dating  For Your Enjoyment In Greater Kailash,New Delhi Call 9990644489

### ISSUE THREAD

**Issue by delhimunirka** [github/explore#1099]
Indian Dating  For Your Enjoyment In Greater Kailash,New Delhi Call 9990644489

**Comment by KaycoinsInc** [comment]
Is this a joke

**Comment by bigjohn1718** [comment]
Is what a joke?Sent from my Metro By T-Mobile 4G LTE Android Device
-------- Original message --------From: "KayKutee.eth" <notifications@github.com> Date: 9/29/19  10:04 PM  (GMT-05:00) To: github/explore <explore@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [github/explore] Indian Dating  For Your Enjoyment In Greater Kailash,New Delhi Call 9990644489 (#1099) Is this a joke

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/github/explore/issues/1099?email_source=notifications\u0026email_token=ANK3WUVEOIFQ7SI2A7J3EBDQMFNCXA5CNFSM4I3Q6HEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD74F52Q#issuecomment-536370922",
"url": "https://github.com/github/explore/issues/1099?email_source=notifications\u0026email_token=ANK3WUVEOIFQ7SI2A7J3EBDQMFNCXA5CNFSM4I3Q6HEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD74F52Q#issuecomment-536370922",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
