### ISSUE TITLE
How to hide or disable "Issues" view on github topics pages?

### ISSUE THREAD

**Issue by evdcush** [github/explore#1308]
The Issues tab/view of repos on topics makes exploring new projects difficult. 

I like to browse topics to *discover* new projects and topics. The Issues tab/view obscures relevant top-level information about a project, instead showing a preview of a single issue on the repo. The issues view does not give me any information of interest.

Please see the screenshot from the github.com/topics/robotics page for reference:

![Robotics topics](http://i.imgur.com/G5BF7hL.png "Issues view")

## Code view :relaxed:
Repos that are on the original "Code" tab provide all the info necessary to grok the project's contents and purpose. For example, from the **description** of "AtsushiSakai/PythonRobotics", I can assume it is a repository containing "python sample codes for robotics algorithms, from the **topics** that "python" "robotics" and "algorithm" are key parts of the repo, and from the **language** indicator that it is mostly in notebooks.

## Issues view :persevere: 
"hybridgroup/gobot" is unfortunately in Issues view, and it is not clear to me, as the user, what the project is about, why it is featured in 'robotics' topics, or why I should be concerned with the featured Issue. 

I don't know anything about "gobot," so why should I be concerned with one user's need to use the gobot framework to leverage "MQTTbot events" to control the "TelloBot Driver"?

I would rather know **what** gobot is about.

# How to disable "Issues"?
I would like to **only** see the "code" view (how topics used to be), and not see Issues or any other tab. 

How can I display topics in this manner?

**Comment by Arpitkm** [comment]
Just go to your settings tab  in GitHub, scroll down and your find under features -> 'issues', just
unmark it, and the issues tab will become hidden.

**Comment by evdcush** [comment]
@Arpitkm Thanks  for the tip. Would you mind clarifying where to find this setting? 

I could not find anything related to 'issues' in the normal settings dashboard:

![Settings view](http://i.imgur.com/6CrkRml.png)


Or in that hamburger menu:

![User hamburger](http://i.imgur.com/4zzk7n2.png)


When I click on "Feature preview," it only showed a "Codeowners" setting--nothing for toggling 'issues'.

**Comment by daledude** [comment]
@Arpitkm doesn't understand what your talking about, @evdcush. He's talking about disabling issues for **YOUR** project.

I noticed that showing the issues tab randomly for projects while **Exploring Topics** happened fairly recently. If the project description was still shown then this wouldn't be such a confusing change. But, why **would I care** about a projects issues **if I don't even know what the project is**. I'm not privy to numbers but I would assume a lot of projects will be skipped because of this. Everyone of my colleagues, friends and other random people I've spoke to about it skip all projects that don't display the description. Or, don't even use Explore/Topics because it's fairly useless for, well, finding new and interesting related projects. i.e. Exploring.

Unfortunately, this project is about the data and not how it's presented to us as users. Expect to be ignored. *shrug*

**Comment by jbltx** [comment]
+1 I always look for interesting new projects, but I am upset about these **Issues** tab one the topic results page. If at least we could click on the **Code** to see the readme content instead of redirecting user to the repository, it will be useful.

**Comment by samuei** [comment]
I believe (and I could be wrong) that this is the wrong place to suggest this. This is just the community content info for the Topics and Collections tabs of the Explore area. The actual engine for recommendations seems to be drawing from the same code as the site's search functionality (which _also_ shows issues without an option to disable). Since I don't see a repo for that, I would assume the proper place to suggest this would be in the [Community Forum](https://github.community/).

Whether @github will address feedback from there or not, I can't say.

**Comment by evdcush** [comment]
@samuei I tried posting on Community Forum. 

Was promptly removed as "spam"... :disappointed: 

No idea where to post this, because these issues are clearly not moderated or maintained by github. I'm looking into whether it's possible to make a browser extension or something that only shows "code" view.

**Comment by samuei** [comment]
That's not encouraging. 🙁 

Neither is that "Contact Github" at the bottom of this page leads to an FAQ instead of something that lets you contact Github...but the "Contact us" link inside that FAQ does! Maybe submitting something [here](https://support.github.com/contact) will work, then.

If not, then I'm out of ideas.

**Comment by daledude** [comment]
I posted on the forum before Christmas last year without reply.
https://github.community/t5/How-to-use-Git-and-GitHub/Topic-list-showing-project-issues-and-not-its-description/m-p/41686

I also opened a ticket that replied with forwarding to tech team.

I think a post on programming reddit needs to happen to let dev's know they're losing exposure over this dumb change.

**Comment by MikeMcQuaid** [comment]
> How to disable "Issues"?

This is not possible, sorry.

**Comment by evdcush** [comment]
> > How to disable "Issues"?
> 
> This is not possible, sorry.

Oof.

I wouldn't consider this closed.

**Comment by MikeMcQuaid** [comment]
@evdcush This is not a repository for GitHub product feedback.
