### ISSUE TITLE
Payeer

### ISSUE THREAD

**Issue by dungphan61** [github/explore#625]
Check Visa number or Mastercard

**Comment by jwest1144** [comment]
Huh

**Comment by Juan1113** [comment]
Possibly scan your card rather then manually typing in the 16 digit account # , it is long an is easy to accidentally add the wrong digit or even miss a digit, you may also set up your Google amount so that it will automatically save your payment details an Google will automatically fill in payment info. Much faster and easier I have found an I use the feature myself.

**Comment by mandylatsonMRGL** [comment]
bitcoin:?r=https://bitpay.com/i/2Fh7AFb7ukT4hUMcKvXKD2
