### ISSUE TITLE
Embed on Website is not available

### ISSUE THREAD

**Issue by ClausGamborg** [github/explore#881]
Hello

I have created studies for all chess openings on lichess.org but cannot be shown on website. Embed as before. Like Eco Code E77 to E99:

Embeded on website: https://www.cleanchess.com/kings-indian-eco-code-e77-e99.html 

On lichess.org: https://lichess.org/study/uSxlen6h

Do you make it possible again to show chess openings on website or I have to delete all chess openings on lichess.org?

Best Regards
Claus Gamborg

**Comment by smde925** [comment]
To incubate posterity, there must be masters on the prowl to defend and behold, my invited, your time is now! :

Suspected root cause - pnp permissioning aberations resulting in sub-optimal outcomes for the certifable primary owner and sponsor which has been raised on a Github public access access for public consumption or locally on affected devices / environments during any  / all intranet / internet / www outages.

Intended / Ideal outcome - no changes to code  / environment / authentication / permissions scheme / profile configurations / hosting / platform changes / hijacks / code changes /  unauthorized read/write issuance to third parties; an immediate revocation to those whom are not the certifiable primary owner and sponsor (only governing principals/les);

The certifiable primary owner and sponsor plus all stakeholders must ensure full waterfall project lifecycle participation Is agreed upon prior to project kickoff. Any stakeholder working on any element of code / environment / authentication / permissions scheme / profile configurations / hosting / platform changes beyond phase one withhout the certifiable primary owner and sponsor "PPE acknowledgement" artifact posted on the mandated Github public access site by which he will provide the location address for any / all project data / artifacts which he will provide the site location during initial project kickoff meeting. If any element of work is underway or location address not available and provided by for any / all reasons, then project shall cease work immediatly as all stakeholders are in violation of the governing principles mentioned above and in violation of the noble participation behaviors referenced below.
